---
apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: osia
  title: Osia
  namespace: quality-community
  description: |
    Tool for unified installer of OpenShift to various clouds which is easy to automate and use within CI.
  annotations:
    github.com/project-slug: 'redhat-cop/osia'
  tags:
    - language:python
    - category:cloud
    - ecosystem:openshift
    - ecosystem:public
  links:
    - title: Help
      url: https://github.com/redhat-cop/osia/blob/devel/README.md
      icon: help
    - title: Documentation
      url: https://osia-python.readthedocs.io/en/latest/
spec:
  owner: group:redhat/osia-devel
  domain: quality-community/quality-community
